#!/usr/bin/env bash

# installing xcode dev tools
xcode-select --install

# Check for Homebrew and install if we don't have it
if [ ! $(command -v brew) ]; then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Update Homebrew recipes
brew update

# Install all our dependencies with bundle (See Brewfile)
brew tap homebrew/bundle
brew bundle install --file ${DOTFILES}/Brewfile

# Running instalation of backblaze
if [ ! -e "/Applications/Backblaze.app" ]; then
  open '/usr/local/Caskroom/backblaze/latest/Backblaze Installer.app'
fi

# start a service to rotate IAM access keys
brew services start rhyeal/aws-rotate-iam-keys/aws-rotate-iam-keys

# prepend changes for par_reattach in /etc/pam.d/sudo
echo -e "# --- [start] pam_reattach changes\nauth       optional       pam_reattach.so\nauth       sufficient     pam_tid.so\n# --- [end] parm_reattach changes\n$(cat /etc/pam.d/sudo)" | sudo tee /etc/pam.d/sudo
